### ISSUE TITLE
Avatars in conversation list sidebar have gray hairline

### ISSUE THREAD

**Issue by bentuna** [nextcloud/spreed#13324]
## Steps to reproduce
1. Open talk and look at an avatar of a group conversation in the left sidebar.
2. See the dark gray hairline around the avatar image.

### Expected behaviour

- There should be no hairline.
- Also, there could be more contrast on light backgrounds, so adding a white Border to the avatars would solve the problem.
- Also, it makes little sense to display a dark border around the user status when using dark mode, when in the top menu the icon color is determined by the custom background and not by light or dark mode.

## Talk app
**Talk app version:** 19.0.9

## Screenshots

| | before | after
| --- | --- | --- |
| light | ![Bildschirmfoto 2024-09-17 um 11 53 47](https://github.com/user-attachments/assets/e239f535-6560-431c-803c-d2fd88970a26) | ![Bildschirmfoto 2024-09-17 um 11 52 23](https://github.com/user-attachments/assets/528d4395-cbed-4db8-b232-fb844dd6de31)
| dark | ![Bildschirmfoto 2024-09-17 um 11 53 26](https://github.com/user-attachments/assets/2fddd3ef-e361-441c-bbd6-6b919e3609bc) | ![Bildschirmfoto 2024-09-17 um 11 51 35](https://github.com/user-attachments/assets/9f58d091-caad-4f7a-b012-1163a4ccbb9e)

| | before | after
| --- | --- | --- |
| light | ![Bildschirmfoto 2024-09-17 um 11 54 28](https://github.com/user-attachments/assets/8e00085e-bf38-4e29-bfc1-c03498b876e6) | ![Bildschirmfoto 2024-09-17 um 12 22 52](https://github.com/user-attachments/assets/6ee52770-8d37-4f54-b96b-693a9d6a3351)
| dark | ![Bildschirmfoto 2024-09-17 um 12 20 44](https://github.com/user-attachments/assets/ce904d92-b86c-40e5-bfda-e6b8de8eabab) | ![Bildschirmfoto 2024-09-17 um 12 03 41](https://github.com/user-attachments/assets/e432a810-208b-4a23-ab69-575808259a7a)

## CSS
```css
/* Talk avatars */
.conversation-icon .avatar.icon { background-color: var(--color-main-background) !important }
.avatar, .conversation-icon .avatardiv.conversation-icon__avatar:not(.avatardiv--unknown), .button-vue__wrapper .button-vue__icon .avatardiv.user-menu__avatar:not(.avatardiv--unknown) { border: 3px solid var(--color-main-background) !important; background-color: var(--color-main-background) !important}
.avatardiv .avatardiv__user-status { border: 2px solid var(--color-main-background) !important; background-color: var(--color-main-background) !important}
/* Top menu avatar */
.user-menu .button-vue__wrapper .button-vue__icon .avatardiv.user-menu__avatar:not(.avatardiv--unknown) { border: 3px solid var(--color-primary-text) !important; background-color: var(--color-primary-text) !important}
.user-menu .button-vue__icon .avatardiv .avatardiv__user-status { border: 2px solid var(--color-primary-text) !important; background-color: var(--color-primary-text) !important}
```
